Repository astropenguin/xarray-dataclasses, pull requests merged in 2021-04, with the labels that each got.

#43 Fix type hints
  .github/workflows/tests.yml
  .gitignore
  package-lock.json
  package.json
  pyrightconfig.json
  xarray_dataclasses/common.py
  xarray_dataclasses/dataarray.py
  xarray_dataclasses/dataset.py
  xarray_dataclasses/typing.py
  xarray_dataclasses/utils.py
Labels: bug

#45 Fix wrong comment
  xarray_dataclasses/typing.py
Labels: bug, docs

#40 loosen Xarray dependency requirements
  pyproject.toml
Labels: feature
