Repository astropenguin/xarray-dataclasses, pull requests merged in 2022-09, with the labels that each got.

#165 Update version range of typing-extensions (>=3.10, <5.0)
  poetry.lock
  pyproject.toml
Labels: dependencies

#168 Add support for Poetry >=1.2
  .devcontainer/Dockerfile
  poetry.lock
  pyproject.toml
Labels: dependencies

#169 Release v1.3.0
  .zenodo.json
  CITATION.ctf
  README.md
  docs/_static/logo-dark.svg
  docs/_static/logo-light.svg
  docs/conf.py
  poetry.lock
  pyproject.toml
  xarray_dataclasses/__init__.py
Labels: release

#171 Release v1.3.1
  CITATION.cff
  README.md
  pyproject.toml
  xarray_dataclasses/__init__.py
Labels: docs, release
